apiVersion: diagnostics.office.com/v1beta1
kind: ProcessDump
metadata:
  name: dump-with-pid
spec:
  podName: windows-deployment-667c466f67-88h5s
  processName: ""
  processID: 8524
  containerName: ""

