apiVersion: diagnostics.office.com/v1beta1
kind: ProcessDump
metadata:
  name: dump-with-pname # any name you like
spec:
  podName: windows-deployment-667c466f67-88h5s # the pod where target process resides
  processName: "consoleapp0" # name of target process
  containerName: "" # the container where target process resides

