apiVersion: v1
kind: Pod
metadata:
  name: testworker
spec:
  containers:
  - name: worker
    image: ic3suzhouswat.azurecr.io/sample-client:latest
    env:
    - name: POD_NAME
      value: "windows-deployment-667c466f67-88h5s"
    - name: PROCESS_NAME
      value: "consoleapp0"
    - name: CONTAINER_NAME
      value: ""
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  nodeSelector:
    kubernetes.io/os: "linux"
