apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
spec:
  containers:
  - name: worker
    image: mqiaoacr.azurecr.io/sample-client:latest
    env:
    - name: POD_NAME
      value: "target-deployment-5cf5db59dd-j2jq5"
    - name: CONTAINER_NAME
      value: ""
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
